name: Monitor Ahara Website

concurrency:
  group: ration-monitor
  cancel-in-progress: true
  
on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor
        id: monitor
        run: |
          python monitor.py
        continue-on-error: true

- name: Commit updated hash
  run: |
    git config user.name "github-actions"
    git config user.email "actions@github.com"

    git pull --rebase

    git add last_hash.txt

    git diff --cached --quiet || git commit -m "Update hash"

    git push

      - name: Create issue if changed
        if: steps.monitor.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Ahara website changed"
          content-filepath: .github/ISSUE_TEMPLATE.md